In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

In [8]:
names = ["K-Nearest Neighbors",
        "Linear SVM",
        "Decision Tree",
        "Multilayer Perceptron",
        "Gaussian Naive Bayes",
        "Random Forest"
]

classifiers = [KNeighborsClassifier(3),
              SVC(kernel="linear", C=0.025),
              DecisionTreeClassifier(max_depth=5),
              MLPClassifier(alpha=1, max_iter=10000),
              GaussianNB(),
              RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
]

df = pd.read_csv("iris_data.csv")
df

     sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [9]:
df.head()
#df = df.drop("Id", axis=1)
#df.head()

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [10]:
X = df.iloc[:, :-1]
X.head()
y = df.iloc[:, -1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

In [11]:
from sklearn.preprocessing import LabelEncoder
y = LabelEncoder().fit_transform(y)
y = pd.DataFrame(y)
y.head()

   0
0  0
1  0
2  0
3  0
4  0

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
for name, clf in zip(names, classifiers):
 clf.fit(X_train, y_train.values.ravel())
 score = clf.score(X_test, y_test)
 print("Classifier Name: ", name, "Score: ", score)

Classifier Name:  K-Nearest Neighbors Score:  0.98
Classifier Name:  Linear SVM Score:  0.96
Classifier Name:  Decision Tree Score:  0.98
Classifier Name:  Multilayer Perceptron Score:  0.98
Classifier Name:  Gaussian Naive Bayes Score:  0.96
Classifier Name:  Random Forest Score:  0.98